- src/pages/Booth/Election/QuestionSection/MixnetSelection.jsx
Se cambia el color de las opciones deshabilitadas en mixnet
> Change color disabled option

- src/pages/Booth/Election/CabinaElection.jsx
- src/pages/Booth/components/VerifyVoteModal.jsx
Se corrige el botón de enviar voto en la cabina
> Fix send button cabina

- src/pages/Admin/CreateQuestion.js/CreateQuestion.jsx
- src/pages/Admin/CreateQuestion.js/component/QuestionsForms.jsx
- src/pages/Booth/Election/QuestionSection/MixnetSelection.jsx
Se añade group votes para mixnet
> Add group votes for mixnet

- src/static/booth/js/jscrypto/jsbn.js
Se añade am4 para aumentar eficiencia en motores de firefox
> add am4 for jsbn

- src/constants.js
- src/pages/Booth/Panel/VerifyElection.jsx
- src/pages/Booth/Panel/VerifyInstructions/CardInstruction.jsx
- src/pages/Booth/Panel/VerifyInstructions/Step1Descript.jsx
- src/pages/Booth/Panel/VerifyInstructions/Step2Descript.jsx
- src/pages/Booth/Panel/VerifyInstructions/Step3Descript.jsx
- src/static/assets_home/css/Home.css
Mostrar al usuario las instrucciones que debe seguir para verificar los resultados de determinada elección.
Crear una vista que explique paso a paso como verificar, de manera auto-contenida. Es decir, que se puede llegar a toda la información necesaria para realizar el proceso a partir de la interfaz.
- El enlace para descargar el resumen matemático de la elección está _hardcodeado_. Este se debe obtener desde la información de cada elección o del admin de esta.
- En las instrucciones se le llama _resumen matemático_ a lo que conocemos como _Bundle_. Esto tiene como finalidad que el término sea más comprensible para las y los usuarios.
> Verificación de una elección

- src/pages/Admin/CustodioClaves/DecryptProve.jsx
- src/pages/Booth/Election/CabinaElection.jsx
Se añade feedback para el custodio a la hora de enviar las desencriptaciones.
> Add user feedback to decrypt prove

- src/pages/Admin/CustodioClaves/DecryptProve.jsx
- src/pages/Admin/CustodioClaves/decrypt-worker.js
- src/static/booth/js/jscrypto/heliosc-trustee.js
- src/static/booth/js/jscrypto/tally.js
Desencriptación en paralelo
Se busca reducir el tiempo de la subida de desencriptaciones parciales de los custodios aplicando paralelización
Se hace el uso de workers de js a los cuales se les entrega una porción del Tally. Una vez completado el proceso de cada worker se deposita en un storage a la espera de que todos terminen y se ordene, esto para cada pregunta.
Por mi parte lo probe mucho en mixnet y homomorfica pero aun requiere más repaso dado que es una parte critica del sistema.
> Desencriptación en paralelo

- src/pages/Admin/Home/component/Accordion.jsx
> fix: improve admin menu list #46

- src/pages/Admin/Home/HomeAdmin.jsx
- src/utils/utils.jsx
Correción error en el buscador de elecciones
Se corrige error del buscador de elecciones, ahora considera tanto el name como el short name sin puntuación
> fix search election

- src/pages/Admin/CreateElection/CreateElection.jsx
- src/pages/Admin/component/AlertNotification.jsx
- src/static/assets_home/css/Home.css
Arreglo de verificación del nombre corto de una elección
Se arregla la verificación de la creación de la elección con nombres cortos
> fix check short name election

- src/App.js
- src/component/ShortNavBar/UserButton.jsx
- src/pages/Admin/AdministrationPanel/component/ModalCloseElection.jsx
- src/pages/Admin/AdministrationPanel/component/ModalCombineTally.jsx
- src/pages/Admin/AdministrationPanel/component/ModalDeleteElection.jsx
- src/pages/Admin/AdministrationPanel/component/ModalFreeze.jsx
- src/pages/Admin/AdministrationPanel/component/ModalTally.jsx
- src/pages/Admin/CreateElection/CreateElection.jsx
- src/pages/Admin/CreateQuestion.js/CreateQuestion.jsx
- src/pages/Admin/CustodioClaves/CreateCustodio.jsx
- src/pages/Admin/CustodioClaves/DecryptProve.jsx
- src/pages/Admin/CustodioClaves/Keygenerator.jsx
- src/pages/Admin/CustodioClaves/components/ModalDeleteCustodio.jsx
- src/pages/Admin/Login/Login.jsx
- src/pages/Admin/Statistics/Sections/InvalidLogginByTime.jsx
- src/pages/Admin/Statistics/Sections/LogginByTime.jsx
- src/pages/Admin/VotersList/components/DeleteModal.jsx
- src/pages/Admin/VotersList/components/DeleteVoterModal.jsx
- src/pages/Admin/VotersList/components/EditVoterModal.jsx
- src/pages/Admin/VotersList/components/SettingsUrna.jsx
- src/pages/Admin/VotersList/components/UploadModal.jsx
- src/pages/Auth/RequireAuth.jsx
- src/pages/Booth/Booth.jsx
- src/services/election.js
- src/services/trustee.js
- src/utils/utils.jsx
Cambio de storage por local y inactividad
Se cambia la forma de guardar el token de logueo para permitir usar distintas pestañas. También se agrega periodo de inactividad de 10 minutos para el apartado de admin
> change storage for login

- src/pages/Booth/components/CastDone/ValidatedVote.jsx
Feedback boton bundle
Feedback para el boton de descarga del archivo de bundle. Al hacer click muestra que se esta generando con un icono de carga y cuando termina se indica que se descarga.
> add feedback to download bundle

- src/constants.js
- src/pages/Admin/ElectionResume/components/WeightsTable.jsx
- src/pages/Admin/Results/components/Results.jsx
- src/pages/Admin/Statistics/Sections/VotesByTime.jsx
- src/pages/Booth/Panel/CastVoteView.jsx
- src/pages/Booth/Panel/Logs.jsx
- src/pages/Booth/Panel/StatisticsBooth.jsx
- src/pages/Booth/Panel/VerifyElection.jsx
- src/pages/Booth/Panel/VerifyInstructions/Step2Descript.jsx
- src/pages/Booth/Panel/VerifyInstructions/Step3Descript.jsx
- src/pages/Booth/Panel/components/CardsInfoElection.jsx
- src/pages/Booth/components/NotAvalaibleMessage.jsx
- src/static/assets_home/css/Home.css
Revisar flujos del Portal de Información (perspectiva del votante y del observador).
En distintas etapas del proceso, algunas vistas del panel de información muestran mensaje default. Este mensaje debe ser enunciado con el mismo tono en todos los casos y bajo el mismo estilo.
Algunas son modificadas para otorgar mayor claridad y otras se reescriben para cumplir con el formato (camel case, minúscula, mayúscula, etc).
Se debe tratar al usuario de usted
> [QA] Portal de información

- src/static/assets_home/css/Home.css
En el portal de informaciones, sección resultados, se debe poder seleccionar el nombre de los candidatos a partir de las tablas.
Se hacen modificaciones para que todo el texto dentro de las tablas sea seleccionable.
Se puede copiar y pegar el contenido de las tablas sin problemas.
> [FIX] Seleccionar el texto de las tablas

- src/constants.js
- src/pages/Admin/CustodioClaves/DecryptProve.jsx
- src/pages/Admin/CustodioClaves/decrypt-worker.js
- src/pages/Booth/Panel/CastVoteView.jsx
Github Issues
Se corrigen ciertas cosas levantas por QA. Estas son #81 #77 y #73
> github issues

- src/pages/Admin/CustodioClaves/CustodioHome.jsx
- src/pages/Admin/CustodioClaves/Keygenerator.jsx
- src/pages/Admin/CustodioClaves/components/DropFile.jsx
Revisar el funcionamiento del portal de custodios.
- Generación de claves
- Desencriptación parcial
Se contempló la posibilidad de especificar para el usuario los siguientes tres pasos para la generación de claves:
1. Generar y descargar
2. Verificar
3. Sincronización con los otros custodios
Esto se comenzó a implementar, pero no se finalizó, debido a que el tiempo que estaba tomando era mucho frente al beneficio que brindaba.
Si en algún momento se decide retomar este punto se puede utilizar el [siguiente PR](https://github.com/clcert/psifos-frontend/pull/78) como base.
Finalmente, se concluyó que la generación de claves está funcionando correctamente, y se realizaron cambios menores en los mensajes mostrados a través del proceso.
Se encontró un BUG que fue reportado mediante un issue.
> [QA] Portal custodios

- src/pages/Admin/Statistics/Graphs/BarPsifosGraph.jsx
- src/pages/Admin/Statistics/Sections/VotesByTime.jsx
Grafico de barras para los votos a través del tiempo
Se agrega el grafico de tipo barras con la opción de mostrar los labels en x sin la fecha del día (solo la hora)
> add bar graph psifos

- src/pages/Booth/Election/CabinaElection.jsx
- src/pages/Booth/components/ProgressBar.jsx
- src/static/assets_home/css/Home.css
- src/static/booth/css/booth.scss
- src/static/svg/ProcesoVotacion/revision_blue.svg
- src/static/svg/ProcesoVotacion/revision_bluelight.svg
- src/static/svg/ProcesoVotacion/revision_gray.svg
- src/static/svg/ProcesoVotacion/revision_green.svg
- src/static/svg/ProcesoVotacion/seleccion_blue.svg
- src/static/svg/ProcesoVotacion/seleccion_bluelight.svg
- src/static/svg/ProcesoVotacion/seleccion_gray.svg
- src/static/svg/ProcesoVotacion/seleccion_green.svg
Actualizar colores y pasos en barra de progreso.
Los colores en la barra tienen un significado:
Gris: Paso pendiente
Azul: Paso actual
Verde: Paso finalizado
Solo se consideran dos pasos:
- Selección
- Revisión
Una vez finalizados estos pasos se muestra una ventana que indica que el proceso fue realizado exitosamente. Todo lo anterior ocurre en la misma url.
> FEATURE Barra de progreso en cabina de votación

- src/pages/Admin/Results/components/PsifosTable.jsx
- src/pages/Booth/Election/QuestionSection/QuestionHeader.jsx
- src/pages/Booth/Election/Review/ReviewQuestions.jsx
Hacer revisión final para cabina de votación en elecciones de preguntas normales y con mixnet.
Mejorar resposividad y distribución de los elementos.
> QA Cabina Votación

- src/pages/Admin/CreateQuestion.js/component/AnswersQuestions.jsx
- src/pages/Admin/CreateQuestion.js/component/DeleteQuestionButton.jsx
- src/pages/Admin/CreateQuestion.js/component/GroupApplicationsCheckbox.jsx
- src/pages/Admin/CreateQuestion.js/component/IncludeBlankNullCheckbox.jsx
- src/pages/Admin/CreateQuestion.js/component/OptionQuestions.jsx
- src/pages/Admin/CreateQuestion.js/component/QuestionStatementInput.jsx
- src/pages/Admin/CreateQuestion.js/component/QuestionTypeSelector.jsx
- src/pages/Admin/CreateQuestion.js/component/QuestionsForms.jsx
- src/pages/Admin/utils.jsx
Hacer QA en formulario de creación de una pregunta
Corregir elementos de la interfaz, hacer refactor y corregir los siguientes bugs.
REPRO
Crear una elección
Crear una pregunta sesteando las preguntas de la siguiente manera
- Crear una respuesta r1
- Crear una respuesta r2
- Borrar r1 (dejar r2)
- Crear otra respuesta r3
ESPERADO
La respuesta r3 se crea correctamente, independiente del resto
BUG
Al sestear r3 se modifica también r2 y aparece el siguiente warning 
Encountered two children with the same key, `1`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
REPRO
Crear pregunta cerrada
Agregar respuesta y escribir la …
> FIX create question form

- src/constants.js
- src/pages/Admin/AdministrationPanel/AdministrationPanel.jsx
- src/pages/Admin/AdministrationPanel/component/CardSteps.jsx
- src/pages/Admin/AdministrationPanel/component/ModalReleaseResults.jsx
- src/pages/Admin/AdministrationPanel/component/Status.jsx
- src/pages/Admin/Results/Results.jsx
- src/pages/Booth/Panel/VerifyElection.jsx
Estado de resultados liberados
Se agrega un nuevo estado a las elecciones que corresponde a la acción de liberar los resultados, ahora cuando se combinan las desencriptaciones parciales se genera un nuevo paso manual para que los resultados sean liberados al publico.
> add election results release

- src/pages/Admin/VotersList/components/VotersTable.jsx
Borrar votantes durante una elección
Con este cambio se pueden eliminar votantes siempre y cuando no hayan depositado un voto en la urna
> delete voter in election

- src/constants.js
- src/pages/Admin/Results/Results.jsx
- src/pages/Admin/Results/ResultsPerQuestion.jsx
- src/pages/Admin/Results/parseResult.js
- src/pages/Admin/utils.jsx
- src/pages/Booth/Election/CabinaElection.jsx
- src/pages/Booth/Election/QuestionSection/QuestionElection.jsx
- src/pages/Booth/Election/QuestionSection/QuestionHeader.jsx
- src/pages/Booth/Election/QuestionSection/Questions/InputRanking.jsx
- src/pages/Booth/Election/QuestionSection/RankingSelection.jsx
- src/pages/Booth/Election/Review/TextSelected.jsx
- src/static/booth/js/boothworker-single.worker.js
- src/static/booth/js/jscrypto/encypted-answers.js
- src/static/booth/js/jscrypto/tally.js
Recibir una papeleta de ranking preferencial y ponerla en formato para enviarla al back.
Hasta el momento se ha imitado la metodología que siguen las elecciones con mixnet.
Crear una elección
Añadirle una pregunta tipo STV con las siguientes características:
- Que no incluya votos nulos y blancos
- Con como máxima cantidad de respuestas 6
- Con 6 respuestas diferentes
Ingresar a la cabina de votación y votar.
- Aun no se define en qué casos se permitirán votos nulos y blancos, por lo que hasta el momento este caso no soporta este tipo de votos y es necesario excluirlos especificándolo en el formulario de creación de preguntas. El formulario de creación de preguntas debería excluirlo automáticamanete.
- En este momento, el número máximo de respuestas en el formulario de creación de …
> FEAT Trabajar una papeleta con ranking preferencial

- src/pages/Admin/AdministrationPanel/component/CardInfo.jsx
- src/pages/Admin/CreateElection/CreateElection.jsx
- src/pages/Admin/CustodioClaves/DecryptProve.jsx
- src/pages/Admin/Results/CalculatedResults.jsx
- src/pages/Admin/Results/Results.jsx
- src/pages/Admin/Results/ResultsPerQuestion.jsx
Elecciones con multiple grupo
Se quieren hacer elecciones con multiples grupos, categorizando a los votantes. Para lograr esto debemos separar el tally.
Se necesitan subir votantes donde su ultimo valor del archivo corresponde al nombre del grupo donde perteneces, si estos no tienen no se le asigna grupo (las elecciones abiertas no van con grupo)
> Election multi group

- src/pages/Admin/AdministrationPanel/component/CardSettings.jsx
- src/pages/Admin/AdministrationPanel/component/Status.jsx
- src/pages/Admin/Results/Results.jsx
- src/pages/Admin/Results/ResultsView.jsx
Cambios en liberar resultado
Ahora cuando las desencriptaciones son combinadas el administrador puede ver los resultados y también tiene la opción de liberarlos. Para el portal solo se verán cuando el admin los libere.
> release results only portal

- src/pages/Admin/ElectionResume/components/InfoElection.jsx
- src/pages/Admin/ElectionResume/components/ResumeTable.jsx
- src/pages/Admin/ElectionResume/components/WeightsTable.jsx
- src/pages/Admin/Results/CalculatedResults.jsx
- src/pages/Admin/Results/Results.jsx
- src/pages/Admin/Results/ResumeElection.jsx
- src/pages/Admin/Results/ResumeWeights.jsx
- src/pages/Admin/VotersList/components/VotersTable.jsx
- src/pages/Booth/Panel/components/CardsInfoElection.jsx
- src/services/election.js
Se actualiza la forma en que se muestran los resultados agrupados y totales
Se divide la sección en dos cuando la opción de agrupados esta activa
> update results view

- src/pages/Booth/Panel/components/CardsInfoElection.jsx
Se corrige un error que no permitía que los pesos sean visualizados de manera correcta en el portal de información
Por otro lado se agrego la condición de mostrarlo solo si el peso máximo es mayor a 1
> fix weights portal informacion

- src/pages/Admin/CustodioClaves/CustodioClaves.jsx
- src/pages/Admin/CustodioClaves/components/TrusteesList.jsx
- src/static/assets_home/css/Home.css
Actualización vista de custodio
Se hace una mejora a la vista de los custodios tanto para la versión desktop y mobile, haciendola más intuitiva y una
> Add CopyToClipboard functionality and update UI

- src/constants.js
- src/pages/Admin/CreateQuestion.js/component/AnswersQuestions.jsx
- src/pages/Admin/CreateQuestion.js/component/DeleteQuestionButton.jsx
- src/pages/Admin/CreateQuestion.js/component/GroupApplicationsCheckbox.jsx
- src/pages/Admin/CreateQuestion.js/component/OptionQuestions.jsx
- src/pages/Admin/CreateQuestion.js/component/QuestionStatementInput.jsx
- src/pages/Admin/CreateQuestion.js/component/QuestionTypeSelector.jsx
- src/pages/Admin/CreateQuestion.js/component/QuestionsForms.jsx
- src/pages/Admin/utils.jsx
- src/pages/Booth/Election/QuestionSection/QuestionElection.jsx
- src/pages/Booth/components/ProgressBar.jsx
- src/static/assets_home/css/Home.css
- src/utils.js
Refact para generalizar nombres de los procesos de manera más cómoda. En particular, para utilizar los nombres definitivos de cada tipo de votación.
Comenzar refactor en formulario de creación de una pregunta.
El formulario luce y funciona igual que antes :)
El código se divide en diferentes componentes, para que en el futuro sea más fácil agregar nuevos tipos de preguntas.
> Create ranking question specification

- src/constants.js
- src/pages/Admin/AdministrationPanel/component/CardInfo.jsx
- src/pages/Admin/AdministrationPanel/component/Status.jsx
- src/pages/Admin/CreateElection/CreateElection.jsx
Elecciones Abiertas, cerradas y semi-cerradas
Se agrega la elección del tipo abierta, la cual permite votar a cualquier persona con el link sin necesidad de autenticación.
Se le entrega un uuid cuando un usuario entra y cuando este envíe un voto el backend genera un votante con nombre y login.
Crear una elección abierta y entrar a votar. Este no debería pedir autenticación y poder votar tranquilamente
> Fix election private login type bug

- src/component/ShortNavBar/ModalHelp.jsx
- src/component/ShortNavBar/MyNavbar.jsx
- src/component/ShortNavBar/NavbarAdmin.jsx
- src/pages/Admin/CustodioClaves/CustodioHome.jsx
- src/pages/Booth/Booth.jsx
- src/pages/Booth/NoAuth.jsx
Modificaciones a la pantalla no autorizada
Se mejora la interfaz de esta vista agregando los siguiente cambios:
- Se agrega la mesa de ayuda para todas las vistas
- Los mensajes son personalizados dependiendo la situación
> refactor no auth view

- src/pages/Admin/Results/QuestionResumes/RankingQuestion/RankingQuestionPerRound.jsx
- src/pages/Admin/Results/QuestionResumes/RankingQuestionResume.jsx
- src/pages/Admin/Results/parseResult.js
Al realizar una elección con varios votos, donde no todos tienen el mismo largo, no se pudieron visualizar los resultados.
Hay valores que en ocasiones pueden ser decimales y estaban siendo tratados como enteros, por lo que en ocasiones se rompía.
Se corrigió también la paleta de colores utilizada en los gráficos.
> Ranking: Bug resultados

- src/pages/Booth/Election/CabinaElection.jsx
- src/pages/Booth/Election/QuestionSection/InputSelection.jsx
- src/pages/Booth/Election/QuestionSection/MixnetSelection.jsx
- src/pages/Booth/Election/QuestionSection/QuestionElection.jsx
- src/pages/Booth/Election/QuestionSection/Questions/InputCheckbox.jsx
- src/pages/Booth/Election/QuestionSection/Questions/InputRadio.jsx
- src/pages/Booth/Panel/CastVoteView.jsx
- src/pages/Booth/Panel/components/CardsInfoElection.jsx
- src/store/index.js
- src/store/slices/boothSlice.js
Añadir estados a la cabina
Se añaden distintos estados para refactorizar el estado actual de la cabina y hacerla más modular
Para probarlo se deben hacer elecciones masivas y cerradas, verificando que el proceso se pueda hacer de manera correcta
> React redux

- src/pages/Booth/Election/QuestionSection/MixnetSelection.jsx
No se puede votar, porque los votos no tienen el largo correcto.
No se puede votar por nulo o blanco.
Cuando se especifica una permutación con más de un candidato, el primer candidato es cambiado por 1.
Se hace pequeño refactor del código y se setean los votos correctamente para cada uno de los casos.
> Fix mixnet elections

- src/pages/Booth/Election/QuestionSection/MixnetSelection/InformalOptions.jsx
- src/pages/Booth/Election/QuestionSection/MixnetSelection/MixnetSelection.jsx
Mejorar la lógica bajo la que se muestran las respuestas informales en la cabina de votación de las elecciones con MN
- Se modifica el estilo de respuestas formales e informales, para que los los elementos utilizadas por ellas sean equivalentes.
- Se separa la lógica de las respuestas informales y se coloca en un nuevo archivo, para identificarlas mas rápidamente.
- Se identifican partes del código que podrían corresponder a funciones auxiliares.
- Se generalizan valores hardcodeados.
- El resultado no se ve reflejado en las interfaces, ya que estas lucen exactamente como lo hacían antes.
- El trabajo realizado no incluye ningún feature nuevo, solo se modifica el estilo del código y se realizan algunas optimizaciones.
Se prueba que el refactor no haya modificado ninguna funcionalidad …
> Style: Improves the informal options logic into the mn booth

- src/colors.js
- src/component/Selector/AsyncSelector.jsx
- src/constants.js
- src/pages/Admin/Statistics/Graphs/BarPsifosGraph.jsx
- src/utils.js
Hacer que el refactor aplicado en la cabina de votación siga la estructura del refacto aplicado en la estructura del código del proyecto.
Crear archivo colors.js, donde se puede leer claramente el texto plano de los colores utilizados en todo el software, sin necesidad de hardcodearlos en cada archivo.
El resultado no se puede observar en las interfaces, ya que es un refactor y no representa cambios respecto de lo que había anteriormente visualmente.
> Refactor: Merge styles
